# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa6d77b08d679d3e79f5d836e68ef519dc2f127926ed18c338ef9315b4a914dcc49e7956801da4f55800ec35f1caa283a9fdec1819eb797b4ac81c93d4c50dc6

test:
  secret_key_base: d603e08ea3575344153ac57bf63a2ccd2d03d147668bbfb152db6f4373ef86b1b743213a3e48abae07d1befafe0783043abfa157e2a912ceb690bd10f9d1c2a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
